### PR TITLE
image_types_ostree: show the errorcode on the push failed warning

### PR DESCRIPTION
**Pull request by quaresmajose**
Signed-off-by: Jose Quaresma <jose.quaresma@foundries.io>

### CODE REVIEW

**Review by pattivacek — APPROVED** [review]
Makes sense, thanks!

**Comment by pattivacek** [comment]
> Can this be backported to kirkstone? I can create a new PR if needed.

Absolutely. If you make a PR I'd be happy to merge it.

**Comment by quaresmajose** [comment]
> > Can this be backported to kirkstone? I can create a new PR if needed.
> 
> Absolutely. If you make a PR I'd be happy to merge it.

Sure, I will crate the PR to kirkstone.

**Comment by quaresmajose** [comment]
Save the stderr/stdout of the `garage-sign targets push` It is a good ideia as it can be added to the warning as well, so I will create a new PR with that.

**Comment by quaresmajose** [comment]
> Save the stderr/stdout of the `garage-sign targets push` It is a good ideia as it can be added to the warning as well, so I will create a new PR with that.

Done in https://github.com/uptane/meta-updater/pull/54

**Pull request merged**
