### PR TITLE
aktualizr: Fix build with gcc-11

### PR DESCRIPTION
**Pull request by shr-project**

### CODE REVIEW

**Comment by shr-project** [comment]
Interestingly it calls hosttools/g++, but this failure is also reproducible with ubuntu-18.04 and langdale (latest oe-core master with gcc-12):

```
FAILED: src/libaktualizr/bootstrap/CMakeFiles/bootstrap.dir/bootstrap.cc.o 
TOPDIR/BUILD/hosttools/g++ -DBOOST_LOG_DYN_LINK -DBUILD_OSTREE -D_FILE_OFFSET_BITS=64 -ITOPDIR/BUILD/work/x86_64-linux/aktualizr-native/1.0+gitAUTOINC+637d1f19d1-7/git/include -ITOPDIR/BUILD/work/x86_64-linux/aktualizr-native/1.0+gitAUTOINC+637d1f19d1-7/git/src/libaktualizr -ITOPDIR/BUILD/work/x86_64-linux/aktualizr-native/1.0+gitAUTOINC+637d1f19d1-7/build/jsoncpp -isystem TOPDIR/BUILD/work/x86_64-linux/aktualizr-native/1.0+gitAUTOINC+637d1f19d1-7/git/third_party/googletest/googletest/include -isystem TOPDIR/BUILD/work/x86_64-linux/aktualizr-native/1.0+gitAUTOINC+637d1f19d1-7/recipe-sysroot-native/usr/include/ostree-1 -isystem TOPDIR/BUILD/work/x86_64-linux/aktualizr-native/1.0+gitAUTOINC+637d1f19d1-7/recipe-sysroot-native/usr/lib/pkgconfig/../../../usr/include/libmount -isystem TOPDIR/BUILD/work/x86_64-linux/aktualizr-native/1.0+gitAUTOINC+637d1f19d1-7/recipe-sysroot-native/usr/lib/pkgconfig/../../../usr/include/blkid -isystem TOPDIR/BUILD/work/x86_64-linux/aktualizr-native/1.0+gitAUTOINC+637d1f19d1-7/recipe-sysroot-native/usr/lib/pkgconfig/../../../usr/include/glib-2.0 -isystem TOPDIR/BUILD/work/x86_64-linux/aktualizr-native/1.0+gitAUTOINC+637d1f19d1-7/recipe-sysroot-native/usr/lib/pkgconfig/../../../usr/lib/glib-2.0/include -isystemTOPDIR/BUILD/work/x86_64-linux/aktualizr-native/1.0+gitAUTOINC+637d1f19d1-7/recipe-sysroot-native/usr/include -O2 -pipe -Wnon-virtual-dtor -DNDEBUG -fPIC   -fstack-protector-all -Wall -Wextra -Wformat-security -Wfloat-equal -Wcast-qual -Wswitch-default -Wconversion -Wlogical-op -Wshadow -std=c++11 -MD -MT src/libaktualizr/bootstrap/CMakeFiles/bootstrap.dir/bootstrap.cc.o -MF src/libaktualizr/bootstrap/CMakeFiles/bootstrap.dir/bootstrap.cc.o.d -o src/libaktualizr/bootstrap/CMakeFiles/bootstrap.dir/bootstrap.cc.o -c TOPDIR/BUILD/work/x86_64-linux/aktualizr-native/1.0+gitAUTOINC+637d1f19d1-7/git/src/libaktualizr/bootstrap/bootstrap.cc
TOPDIR/BUILD/work/x86_64-linux/aktualizr-native/1.0+gitAUTOINC+637d1f19d1-7/git/src/libaktualizr/bootstrap/bootstrap.cc: In constructor ‘Bootstrap::Bootstrap(const boost::filesystem::path&, const string&)’:
TOPDIR/BUILD/work/x86_64-linux/aktualizr-native/1.0+gitAUTOINC+637d1f19d1-7/git/src/libaktualizr/bootstrap/bootstrap.cc:15:20: error: variable ‘std::ifstream as’ has initializer but incomplete type
   15 |   std::ifstream as(provision_path.c_str(), std::ios::in | std::ios::binary);
      |                    ^~~~~~~~~~~~~~
TOPDIR/BUILD/work/x86_64-linux/aktualizr-native/1.0+gitAUTOINC+637d1f19d1-7/git/src/libaktualizr/bootstrap/bootstrap.cc: In static member function ‘static std::string Bootstrap::readServerUrl(const boost::filesystem::path&)’:
TOPDIR/BUILD/work/x86_64-linux/aktualizr-native/1.0+gitAUTOINC+637d1f19d1-7/git/src/libaktualizr/bootstrap/bootstrap.cc:46:22: error: variable ‘std::ifstream as’ has initializer but incomplete type
   46 |     std::ifstream as(provision_path.c_str(), std::ios::in | std::ios::binary);
      |                      ^~~~~~~~~~~~~~
TOPDIR/BUILD/work/x86_64-linux/aktualizr-native/1.0+gitAUTOINC+637d1f19d1-7/git/src/libaktualizr/bootstrap/bootstrap.cc: In static member function ‘static std::string Bootstrap::readServerCa(const boost::filesystem::path&)’:
TOPDIR/BUILD/work/x86_64-linux/aktualizr-native/1.0+gitAUTOINC+637d1f19d1-7/git/src/libaktualizr/bootstrap/bootstrap.cc:63:22: error: variable ‘std::ifstream as’ has initializer but incomplete type
   63 |     std::ifstream as(provision_path.c_str(), std::ios::in | std::ios::binary);
      |                      ^~~~~~~~~~~~~~
```

And there is another issue related to aktualizr-native and that's introduced through ostree-native which depends on target kernel (so aktualizr-native was also depending on target), see the fix for meta-oe:
https://lists.openembedded.org/g/openembedded-devel/message/97094

**Comment by cajun-rat** [comment]
I wonder if this is caused by my recent include-what-you-use changes?  Maybe a `'#include <fstream>` in bootstrap.cc?

**Comment by shr-project** [comment]
> Maybe a '#include <fstream> in bootstrap.cc?

That's what this PR does.

**Comment by pattivacek** [comment]
Let's change this directly in aktualizr, then.

**Comment by cajun-rat** [comment]
> > Maybe a '#include  in bootstrap.cc?
> 
> That's what this PR does.

Lol. That's embarrassing :)

**Comment by cajun-rat** [comment]
Weirdly, it is my IWYU commit [#bf0494df](https://github.com/uptane/aktualizr/commit/bf0494df6382dd26e3daa89d57a393c0ff77f7d8) that actually _adds_ that include. I don't have a meta-updater / Yocto master branch checked out and ready to build, but does bumping [SRCREV](https://github.com/shr-project/meta-updater/blob/jansa/gcc-11/recipes-sota/aktualizr/aktualizr_git.bb#L36) fix it?

**Comment by shr-project** [comment]
I don't have meta-updater build handy right now, but the SRCREV in the recipe seems to be 37 commits behind your fix, so the SRCREV bump might work

https://github.com/uptane/aktualizr/compare/637d1f19d14d3a99fad71d110f5018505b85d2c7...bf0494df6382dd26e3daa89d57a393c0ff77f7d8

**Comment by pattivacek** [comment]
I only really have a dunfell setup right now, but bumping the aktualizr version here should be safe and we should do that regularly anyways.

**Comment by shr-project** [comment]
I've replaced the .patch with SRCREV bump and verified that aktualizr-native builds now with dunfell as well as kirkstone.

**Review by pattivacek — APPROVED** [review]

**Comment by shr-project** [comment]
@cajun-rat Looks like new SRCREV fixed the build with gcc-11, but introduced new build failure with gcc-12 elsewhere.
```
aktualizr-native/1.0+gitAUTOINC+bf0494df63-7/git/src/libaktualizr/package_manager/packagemanagerinterface.cc:26:17: error: field ‘fhandle’ has incomplete type ‘std::ofstream’ {aka ‘std::basic_ofstream<char>’}
|    26 |   std::ofstream fhandle;
|       |                 ^~~~~~~
```

And few other places, will send fix shortly.

**Comment by pattivacek** [comment]
> And few other places, will send fix shortly.

Thanks!

**Pull request merged**
