### PR TITLE
nfs-utils: prefer tmpfiles instead of a custom service

### PR DESCRIPTION
**Pull request by ricardosalveti**
The directories that are critical for nfs-utils at runtime are
/var/lib/nfs, /var/lib/nfs/v4recovery and /var/lib/nfs/statd, which
can easily be created during boot via a systemd tmpfiles, avoiding
the need for a custom service.

While this can be applied in a generic way, having it applied only when
sota is enabled as /var is not preserved only when used with sota/ostree.

Signed-off-by: Ricardo Salveti <ricardo@foundries.io>

### CODE REVIEW

**Comment by pattivacek** [comment]
I think this looks okay, but I'd like to solicit feedback from @liuming50 and @shr-project as they've been involved with that before (see https://github.com/advancedtelematic/meta-updater/pull/753 and https://github.com/advancedtelematic/meta-updater/pull/754).

**Comment by shr-project** [comment]
LGTM

**Comment by ricardosalveti** [comment]
@liuming50 any chance to have a look at this one?

**Comment by pattivacek** [comment]
I think we can safely merge this.

**Pull request merged**
